/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.maptest;

import com.mycompany.maptest.entity.Player;
import com.mycompany.maptest.tile.TileManager;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;

/**
 *
 * @author User
 */
public class GamePane extends javax.swing.JPanel implements Runnable {
    private PaneListener listener;
    private Thread gameThread;
    private KeyHandler keyH = new KeyHandler();
    private TileManager tileM = new TileManager(this);
    private Player player = new Player(this, keyH);
    private boolean isStopped;
    
    Sound music = new Sound();
    
    /**
     * Creates new form GamePane
     */
    public GamePane() {
        initComponents();
    }
    
    public GamePane(PaneListener listener) {
        this();
        this.listener = listener;
        this.setPreferredSize(new Dimension(GameConstants.SCREEN_WIDTH, GameConstants.SCREEN_HEIGHT));
        this.setBackground(Color.white);
        this.setDoubleBuffered(true);
        this.addKeyListener(keyH);
        this.setFocusable(true);
        
        btnBackToMenu.setFocusable(false);
        playMusic(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBackToMenu = new javax.swing.JButton();

        btnBackToMenu.setText("Back to Menu");
        btnBackToMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackToMenuMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBackToMenu)
                .addContainerGap(291, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBackToMenu)
                .addContainerGap(271, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackToMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackToMenuMouseClicked
        // TODO add your handling code here:
        listener.onStartGameClicked(false);
        isStopped = true;
        stopMusic();
    }//GEN-LAST:event_btnBackToMenuMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackToMenu;
    // End of variables declaration//GEN-END:variables

    @Override
    public void addNotify() {
        super.addNotify();
        // This method is called automatically when the panel is 
        // added to the JFrame and becomes displayable.
        if (gameThread == null) {
            startGameThread();
        }
        
        this.requestFocusInWindow();
    }
    
    
    @Override
    public void run() {
        double drawInterval = 1000000000 / 60; // 60 FPS
        double delta = 0;
        long lastTime = System.nanoTime();
        long currentTime;

        while (gameThread != null) { // Check gameThread, not just true

            currentTime = System.nanoTime();
            delta += (currentTime - lastTime) / drawInterval;
            lastTime = currentTime;

            if (delta >= 1) {
                if (!isStopped) { // Only update/repaint if not stopped
                    update();
                    repaint();
                }
                delta--;
            }

            if (isStopped) {
                 break; 
            }
        }
    }
    
    private void startGameThread() {
        gameThread = new Thread(this);
        gameThread.start(); 
    }
    
    private void update() {
        player.update();
    }
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        
        Graphics2D g2 = (Graphics2D) g;
        
        tileM.draw(g2);
        player.draw(g2);
        
    }

    private void playMusic(int i) {
        music.setFile(i);
        music.play();
        music.loop();
    }
    private void stopMusic() {
        music.stop();
    }
}
